### PR TITLE
Use the right link for docs comment in PR

### LINKED ISSUE #45: Comment bot for downloading the documentation seems to be broken
Most likely since I changed something in the CI building of the docs #39 the comment bot who posts a link for downloading in the comments of each PR 

https://github.com/lab-cosmo/software-cookbook/blob/3a073a0c2c8ead4bde227652b2a2f87d86eafb0f/.github/workflows/comment-docs-download.yml#L1-L5

We should try to get this running again.

### PR DESCRIPTION
**Pull request by PicoCentauri**
Fixes #45 

I think the issue was that we now have several artifacts.

I adapted the code from [metatensor](https://github.com/lab-cosmo/metatensor/blob/master/.github/workflows/comment-wheels-pr.yml).

### CODE REVIEW

**Review by Luthaf — APPROVED** [review]
Looks good!

**Comment by PicoCentauri** [comment]
But shouldn't there be a comment or is this only in future PRs?

**Comment by Luthaf** [comment]
these workflow only run if the file is already on master, so it will be used for the next PR

**Comment by DavideTisi** [comment]
eh, should we merge this?

**Comment by Luthaf** [comment]
yes! If it is still broken, we can change the file again.

**Pull request merged**
